### ISSUE TITLE
[meta-issue] Cleanup using features of Arguments

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#311]
#### TODO
Replace `nosimpl` using  `Arguments` option `simpl never`, cf #94. 
This is "broken" up to Coq 8.13 cf #660  https://github.com/coq/coq/issues/13428) 
- [ ] Tune `mask` in a better way? (open question)

#### DONE
- [x] Tune simplification of functions like `nth`, `subn`, cf #95
- [x] cleanup `_head` names #657
  + are there other "volatile" functions?

**Comment by CohenCyril** [comment]
This issue is related to #94 and #95

**Comment by affeldt-aist** [comment]
(I put here the contents of issues #94 and #95 posted by @gares to have related topics in the same place.)
- Use Arguments to declare volatile or simpl never functions
- Use Arguments to tune simplification of functions like nth, subn
  + Many functions consume two inductive arguments in parallel. Arguments lets one block simplification when only one of the two is concrete, improving usability.

**Comment by pi8027** [comment]
Probably a related question: why the `%|` notation in `intdiv` is defined in this way using `\in`? Is this only because of simulating `simpl never`? https://github.com/math-comp/math-comp/blob/3515b33b1245ea169fbaf61405dc60954509fee2/mathcomp/algebra/intdiv.v#L70

**Comment by CohenCyril** [comment]
@pi8027 I think this is because `dvdz` is a member of the algebraic predicate hierarchy (cf https://github.com/math-comp/math-comp/blob/3515b33b1245ea169fbaf61405dc60954509fee2/mathcomp/algebra/intdiv.v#L312) and hence has some canonical properties (https://github.com/math-comp/math-comp/blob/3515b33b1245ea169fbaf61405dc60954509fee2/mathcomp/algebra/intdiv.v#L429-L432). The notation `d %| m` allows easier reuse of these facts.

**Comment by CohenCyril** [comment]
@LaurenceRideau @ybertot @thery this is an unglamorous piece of work... Would one of you be up for it?

**Comment by thery** [comment]
@CohenCyril  not sure I fully understand what exactly needs to be done.

**Comment by chdoc** [comment]
>  not sure I fully understand what exactly needs to be done.

@CohenCyril , me neither. So before everything, I think this issue needs some elaboration on what the issue is.

**Comment by CohenCyril** [comment]
@chdoc, @thery, @LaurenceRideau, @ybertot together with @affeldt-aist we tried to clarify the goals of this PR. Please take a look and tell us if you can attend one of these or otherwise if something is still unclear.
Cheers,

**Comment by CohenCyril** [comment]
Everything that could be done  in 1.12 has been done I think...

**Comment by proux01** [comment]
@CohenCyril the only remaining point here seems to be

> Tune mask in a better way? (open question)

do you remember what that means?

**Comment by CohenCyril** [comment]
> @CohenCyril the only remaining point here seems to be
> 
> > Tune mask in a better way? (open question)
> 
> do you remember what that means?

I think it is related to this: https://github.com/math-comp/math-comp/pull/661#issuecomment-731182232
Otherwise I have no memory.
